CodingGarden/listd

.eslintignore
.prettierignore

This pr Closes #23 by adding the docker-data directory on the .ignores files from prettier and eslint.

Fix: fixing permission denied on lint script at linux enviroment 🚀 

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

This adds two **required** checkboxes for
1- Acknowledge the Code of Conduct
2- Search for Similar Issues.

Update issues template: Acknowledge the Code of Conduct and Search for Similar Issues.

---

.github/workflows/lint.yaml

add actions: lint on PRs

---

CONTRIBUTING.md
README.md

Please check the type of change your PR introduces:
- Moved Google Auth setup docs from Readme.md to CONTRIBUTING.MD

:memo: moved google auth setup to contributing.md

---

.github/PULL_REQUEST_TEMPLATE.md

Please check the type of change your PR introduces:
The "type of PR" list causes it to show tasks that cannot be completed.
Issue Number: #48 
- You no longer select the type of PR since that should be obvious from the Issue that it is related to.

Remove task list from pull request template (issue #48)

---

package-lock.json
package.json
prisma/migrations/20230217214638_init/migration.sql
prisma/schema.prisma
prisma/seeds/data/locales.json
prisma/seeds/index.ts
prisma/seeds/locales.ts
tsconfig.json

**Delete all options except for the one that applies**
- Feature

User settings and locale

---

src/db.server.ts
src/hooks.server.ts

Please check the type of change your PR introduces:
You currently have to make a new prisma instance whenever you need one or export the one currently in hook.server.ts
You have a consistent global prisma instance
- Global prisma added in db.server.ts

feat: #46 shared prisma instance added

---

prisma/migrations/20230218010733_init/migration.sql
prisma/schema.prisma

- Code style update (formatting, renaming)
Some database columns of the table `Account` uses snake case as format. All other columns use camel case, this is inconsistent and should be fixed by using the same format over all tables.
The column names of the `Account` table are using camel case now too.

change the column name format to camel case to have consistent naming

---

src/routes/+layout.server.ts

- Bug fix
I noticed (and tested) that when we add a new route and the user is logged in and onboarded, he will not be able to go to the new route. 
Firstly, I wrote about this [here](https://github.com/CodingGarden/listd/commit/66e467a71ba093a43ece2946f7056ae9120044f9#r101146876), but I decided to do a Pull Request (I hope I did it right 😃).
- changed second if statement in the `src/routes/+layout.server.ts` file
- now, if you create a new route, the user should be able to go to it without redirection to the home page

Fix a problem with redirect if user is onboarded

---

.eslintrc.cjs
src/routes/+layout.svelte
src/routes/+page.svelte
tsconfig.json
vite.config.ts

update eslint and tsconfig closes #58

---

CONTRIBUTING.md

**Delete all options except for the one that applies**
- Code style update (formatting, renaming)
- Other (please describe): Fix typo in URL

Fix issue tracker link in CONTRIBUTING.md

---

.husky/pre-commit
.lintstagedrc.cjs
package-lock.json
package.json

Run typecheck and linter only on staged files.

:sparkles: setup lint-staged fix: #75

---

src/lib/i18n/en/index.ts
src/lib/i18n/i18n-types.ts
src/routes/+page.svelte
src/routes/NavTrail.svelte

Show loading indicators when auth is happening.

:sparkles: add auth loading states fix: #71

---

.eslintrc.cjs
CONTRIBUTING.md
package-lock.json
package.json
src/hooks.server.ts
src/lib/config.server.ts

* Add config loader
* Update contributing guide
* Restrict $env import

:sparkles: add config loader fix: #84

---

src/routes/SEO.svelte

- Bug fix
It doesn't work
- It works
-
-

fix seo component issue

---

src/routes/(protected)/create/+page.svelte

Update the create list form to use "Progressive enhancement"
It stops the page reload, and when the form submission is successful it doesn't refresh; it just redirects.
ref: https://kit.svelte.dev/docs/form-actions#progressive-enhancement-use-enhance
- Refactoring (no functional changes, no API changes)
- Form submits
- If we created the list, the page refresh then we do the goto
- It just works...
- No page reload.
N/A

add use:enhance on create form

---

package-lock.json
package.json
src/app.d.ts
types/types.d.ts

Update major version bump dependencies.

:sparkles: :package: update major dependencies;

---

.github/workflows/checks.yaml
DEVLOG.md

:sparkles: update gh workflow

---

package.json

- Refactoring (no functional changes, no API changes)
no scripts exists to startup the docker container for dev
added better dev experience

added docker-up/down for dev

---

src/app.postcss
src/lib/components/AvatarWithFallback.svelte
src/lib/components/ChannelCard.svelte
src/lib/components/ListCard.svelte
src/routes/+page.server.ts
src/routes/+page.svelte
src/routes/list/[id]/+layout.svelte
tests/editList.test.ts
tests/viewList.test.ts
types/db.ts

**Delete all options except for the one that applies**
- Bug fix
- Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build related changes
- Other (please describe):
-
-
-

:sparkles: add channel avatars to home page

---

vite.config.ts

**Delete all options except for the one that applies**
- Feature
- Build related changes
data-testids are visible to end users which is unnecessary
data-testids are removed unless we are testing

feat: Vite Plugin to remove data-testids unless testing

---

src/routes/(protected)/edit/[id]/+page.server.ts

- Bug fix
- Refactoring (no functional changes, no API changes)
The validation messages are not displayed translated on list edit form.
Issue Number: fixes #159 
The validation messages are translated on list edit form.

:bug: setting locale for list edit form validation messages
